name: Build and Deploy Application
on:
  push:

jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Node js Latest
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run Test cases
        run: npm test    

  build-code-job:
    needs: [run-tests-job]
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish-file-name.outputs.script-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Node js Latest
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Publish JS File name
        id: publish-file-name
        run: echo "script-file=$(basename dist/assets/*.js)" >> $GITHUB_OUTPUT
      - name: Upload the build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist

  deploy-webapp-job:
    needs: build-code-job
    runs-on: ubuntu-latest
    steps:    
      - name: download artifacts
        uses: actions/download-artifact@v7
        with: 
          name: dist-files
          path: dist
      - name: Output the downloaded files
        run: ls -l dist
      - name: Output the script file name
        run: |
          echo "Script file name: ${{ needs.build-code-job.outputs.script-file }}"
      - name: Deploy the web application
        run: echo 'Deploying the web application...'
