name: Test Project
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v7
      - name: install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: install dependencies
        run: npm install